### PR TITLE
Add my profile (Kevin Fotso)

### PR DESCRIPTION
**Pull request by kf-cuanschutz**
I added my information so that they can be integrated into the website.

### CODE REVIEW

**Comment by miltondp** [comment]
Thank you, @kf-cuanschutz! We usually request a review from someone in the lab (this is on the right panel). I assume you want me to review it :) It looks like the preview (see the link in the "PR Preview Action") is not showing your picture/profile. I think it's because the file names must match.

**Comment by kf-cuanschutz** [comment]
@vincerubinetti  do you know why my preview does not work on the website?

**Comment by vincerubinetti** [comment]
This is the same issue as #9.

It looks like almost everyone in this organization has a unique `role`. That's not quite what that field is meant for. There's only meant to be a few high level roles for coarse sorting and determining the type of icon displayed (and the description text below your name if you don't specify a `description`. If you want more specific descriptions of each member, you should use `description`.

**Review by kf-cuanschutz — COMMENTED** [review]
I fixed the role, my profile is showing on the preview.

**Comment by miltondp** [comment]
Hey @vincerubinetti. Thanks for your help. The bot keeps refreshing the publications, but I would like to avoid those changes in this PR (and they also seem incorrect). Is there a way to prevent that?

**Comment by vincerubinetti** [comment]
By default, the template tries to keep your citation details up to date by updating them on any pr activity. To prevent `update-citations.yaml` from running (_without_ preventing `build-preview.yaml` from running), you'd have to [make use of the `paths-filter` action](https://stackoverflow.com/questions/70708306/github-actions-run-step-job-in-a-workflow-if-changes-happen-in-specific-folde) in `on-pull-request.yaml` to conditionally run `update-citations.yaml` only if `_data/sources*.yaml` (or `_data/orcid*.yaml` etc.) were changed. I'll consider this a feature request and perhaps put it in the template, though I would probably leave it commented out because I think it's generally a good idea to update the citations whenever you can (most people don't seem to follow through on their periodic `on-schedule.yaml` citation update PRs).

Regarding the citations being incorrect, the problem seems to be with `doi:10.1093/jamia/ocae139`. Manubot is returning this:

```json
{
    'id': 'JO5qI4J7',
    'type': 'webpage',
    'abstract': 'Pending Publication',
    'language': 'en-GB',
    'note': 'DOI: 10.5555/12345678\nThis CSL Item was generated by Manubot v0.6.0 from its persistent
identifier (standard_id).\nstandard_id: doi:10.1093/jamia/ocae139',
    'title': 'pendingpublications',
    'URL': 'https://doi.org/gtw9d3',
    'accessed': {'date-parts': [['2024', 6, 11]]},
 }
```

And the template is keeping these fields

```json
{
    'id': 'doi:10.1093/jamia/ocae139',
    'title': 'pendingpublications',
    'authors': [],
    'publisher': '',
    'date': '',
    'link': 'https://doi.org/gtw9d3'
}
```

So, this is an upstream Manubot issue.

**Comment by miltondp** [comment]
Thank you, @vincerubinetti! I think I'll wait until the publication is online and the record is updated to merge this PR.

**Pull request merged**
